### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by arokem** [OHSU-Library/Library-Journal-OA-Webinar#1]
Thanks for the nice presentation, and thoughtful comments!

I would love to use slide #5 in a talk that I am preparing.

Adding a Creative Commons attribution license to the repo would allow me to use that, while giving you credit, and linking back to this repo. 

Thanks again!

**Comment by rchampieux** [comment]
Thanks for catching that @arokem - as you can probably tell with threw this repo up then kind of forgot about it 😸 .  I added a CC license to the repo.  Additionally, you're request made me realize that our slide notes didn't attribute the original inspiration for slide 5:  https://www.meetup.com/Berlin-Open-Science-Meetup/photos/26645056/445567759/.  I've added that now!

**Comment by arokem** [comment]
Wonderful. Thank you!
